#cloud-config
write_files:
- content: |
    # BEGIN MANAGED BLOCK
    CONDOR_HOST = 192.168.0.98
    ALLOW_WRITE = *
    ALLOW_READ = $(ALLOW_WRITE)
    ALLOW_ADMINISTRATOR = *
    ALLOW_NEGOTIATOR = $(ALLOW_ADMINISTRATOR)
    ALLOW_CONFIG = $(ALLOW_ADMINISTRATOR)
    ALLOW_DAEMON = $(ALLOW_ADMINISTRATOR)
    ALLOW_OWNER = $(ALLOW_ADMINISTRATOR)
    ALLOW_CLIENT = *
    DAEMON_LIST = MASTER, SCHEDD, STARTD
    FILESYSTEM_DOMAIN = usegalaxy-it
    UID_DOMAIN = galaxy-it
    TRUST_UID_DOMAIN = True
    SOFT_UID_DOMAIN = True
    # run with partitionable slots
    CLAIM_PARTITIONABLE_LEFTOVERS = True
    NUM_SLOTS = 1
    NUM_SLOTS_TYPE_1 = 1
    SLOT_TYPE_1 = 100%
    SLOT_TYPE_1_PARTITIONABLE = True
    ALLOW_PSLOT_PREEMPTION = False
    STARTD.PROPORTIONAL_SWAP_ASSIGNMENT = True
    # END MANAGED BLOCK
    GalaxyTraining = True
    GalaxyGroup = training-beta
    GalaxyCluster = none
    GalaxyDockerHack = False
    STARTD_ATTRS = GalaxyTraining, GalaxyGroup, GalaxyCluster, GalaxyDockerHack
    Rank = StringListMember(MY.GalaxyGroup, TARGET.Group)
  owner: root:root
  path: /etc/condor/condor_config.local
  permissions: '0644'
- content: |
    /data           /etc/auto.data
    /-              /etc/auto.usrlocal
  owner: root:root
  path: /etc/auto.master.d/data.autofs
  permissions: '0644'
- content: |
    share   -rw,hard,intr,nosuid,quota,nfs,nfsvers=4,minorversion=2      192.168.0.249:/data/share
  owner: root:root
  path: /etc/auto.data
  permissions: '0644'
- content: |
    /opt/galaxy        -rw,hard,intr,nosuid,quota,nfs,nfsvers=4,minorversion=2      192.168.0.249:/opt/galaxy
  owner: root:root
  path: /etc/auto.usrlocal
  permissions: '0644'
- content: |
    - name: Install HTCondor executor node
      become: true
      hosts: all
      connection: local
      roles:
        - role: usegalaxy_eu.htcondor
          vars:
            condor_role: execute
            condor_copy_template: false
            condor_host: 192.168.0.98
            condor_password: htcondor
      tasks:
        - name: Disable pulsar
          systemd:
            name: pulsar
            state: stopped
  owner: centos:centos
  path: /home/centos/condor.yml
  permissions: "0644"
packages:
  - ansible
runcmd:
  #- python3 -m pip install ansible # not needed on vgcn image
  - ansible-galaxy install -p /home/centos/roles usegalaxy_eu.htcondor
  - ansible-playbook -i 'localhost,' /home/centos/condor.yml
